DO $$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'finder_app') THEN
        CREATE ROLE finder_app NOLOGIN NOSUPERUSER NOBYPASSRLS;
    END IF;
END $$;

CREATE SCHEMA organizacoes;
CREATE SCHEMA acesso;
CREATE SCHEMA estudantes;
CREATE SCHEMA oportunidades;
CREATE SCHEMA candidaturas;
CREATE SCHEMA autenticacao;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

CREATE TABLE organizacoes.organizacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL CHECK (btrim(nome) <> ''),
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('UNIVERSIDADE', 'EMPRESA', 'INSTITUICAO')),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT current_timestamp
);
CREATE UNIQUE INDEX organizacao_nome_unico ON organizacoes.organizacao(lower(btrim(nome)));

CREATE TABLE acesso.usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacao_id BIGINT NOT NULL REFERENCES organizacoes.organizacao(id),
    nome VARCHAR(120) NOT NULL CHECK (btrim(nome) <> ''),
    login VARCHAR(80) NOT NULL CHECK (login = lower(btrim(login)) AND btrim(login) <> ''),
    senha_hash VARCHAR(255) NOT NULL,
    papel VARCHAR(20) NOT NULL CHECK (papel IN ('ADMIN', 'PUBLICADOR', 'ESTUDANTE')),
    ativo BOOLEAN NOT NULL DEFAULT true,
    versao_acesso BIGINT NOT NULL DEFAULT 0,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    UNIQUE (organizacao_id, id)
);
CREATE UNIQUE INDEX usuario_login_unico ON acesso.usuario(lower(login));
CREATE INDEX usuario_organizacao_nome ON acesso.usuario(organizacao_id, lower(nome));

CREATE TABLE acesso.permissao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recurso VARCHAR(40) NOT NULL,
    acao VARCHAR(40) NOT NULL,
    UNIQUE (recurso, acao)
);
INSERT INTO acesso.permissao(recurso, acao) VALUES
    ('usuarios', 'visualizar'), ('usuarios', 'criar'),
    ('oportunidades', 'visualizar'), ('oportunidades', 'criar'), ('oportunidades', 'editar'),
    ('candidaturas', 'criar'), ('candidaturas', 'visualizar_proprias'),
    ('candidaturas', 'visualizar_organizacao'), ('candidaturas', 'alterar_status'),
    ('perfil', 'editar_proprio');

CREATE TABLE acesso.usuario_permissao (
    organizacao_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    permissao_id BIGINT NOT NULL REFERENCES acesso.permissao(id),
    PRIMARY KEY (organizacao_id, usuario_id, permissao_id),
    FOREIGN KEY (organizacao_id, usuario_id) REFERENCES acesso.usuario(organizacao_id, id)
);

CREATE TABLE estudantes.perfil (
    organizacao_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    campus VARCHAR(100) NOT NULL DEFAULT '',
    curso VARCHAR(120) NOT NULL DEFAULT '',
    periodo VARCHAR(30) NOT NULL DEFAULT '',
    competencias TEXT NOT NULL DEFAULT '',
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    PRIMARY KEY (organizacao_id, usuario_id),
    FOREIGN KEY (organizacao_id, usuario_id) REFERENCES acesso.usuario(organizacao_id, id)
);

CREATE TABLE oportunidades.oportunidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacao_id BIGINT NOT NULL REFERENCES organizacoes.organizacao(id),
    publicador_id BIGINT NOT NULL,
    titulo VARCHAR(140) NOT NULL CHECK (btrim(titulo) <> ''),
    responsavel VARCHAR(120) NOT NULL CHECK (btrim(responsavel) <> ''),
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('ESTAGIO', 'EMPREGO', 'PROJETO', 'EVENTO', 'DESAFIO', 'CAPACITACAO')),
    modalidade VARCHAR(20) NOT NULL CHECK (modalidade IN ('PRESENCIAL', 'HIBRIDO', 'REMOTO')),
    localidade VARCHAR(120) NOT NULL DEFAULT '',
    descricao TEXT NOT NULL CHECK (btrim(descricao) <> ''),
    curso VARCHAR(120) NOT NULL DEFAULT '',
    competencias TEXT NOT NULL DEFAULT '',
    prazo DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'RASCUNHO' CHECK (status IN ('RASCUNHO', 'PUBLICADA', 'ENCERRADA')),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    UNIQUE (organizacao_id, id),
    FOREIGN KEY (organizacao_id, publicador_id) REFERENCES acesso.usuario(organizacao_id, id)
);
CREATE INDEX oportunidade_feed ON oportunidades.oportunidade(organizacao_id, status, criado_em DESC);

CREATE TABLE candidaturas.candidatura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacao_id BIGINT NOT NULL,
    oportunidade_id BIGINT NOT NULL,
    estudante_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ENVIADA' CHECK (status IN ('ENVIADA', 'EM_ANALISE', 'ACEITA', 'RECUSADA')),
    criada_em TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    atualizada_em TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    UNIQUE (organizacao_id, id),
    UNIQUE (organizacao_id, oportunidade_id, estudante_id),
    FOREIGN KEY (organizacao_id, oportunidade_id) REFERENCES oportunidades.oportunidade(organizacao_id, id),
    FOREIGN KEY (organizacao_id, estudante_id) REFERENCES acesso.usuario(organizacao_id, id)
);
CREATE INDEX candidatura_oportunidade ON candidaturas.candidatura(organizacao_id, oportunidade_id, criada_em DESC);
CREATE INDEX candidatura_estudante ON candidaturas.candidatura(organizacao_id, estudante_id, criada_em DESC);

GRANT USAGE ON SCHEMA organizacoes, acesso, estudantes, oportunidades, candidaturas, autenticacao TO finder_app;
GRANT SELECT ON organizacoes.organizacao, acesso.permissao TO finder_app;
GRANT SELECT, INSERT ON acesso.usuario, acesso.usuario_permissao TO finder_app;
GRANT SELECT, INSERT, UPDATE ON estudantes.perfil, oportunidades.oportunidade, candidaturas.candidatura TO finder_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA organizacoes, acesso, oportunidades, candidaturas TO finder_app;

CREATE FUNCTION autenticacao.organizacao_atual() RETURNS BIGINT
LANGUAGE sql STABLE SET search_path = '' AS $$
    SELECT nullif(current_setting('app.organizacao_id', true), '')::bigint
$$;
CREATE FUNCTION autenticacao.usuario_atual() RETURNS BIGINT
LANGUAGE sql STABLE SET search_path = '' AS $$
    SELECT nullif(current_setting('app.usuario_id', true), '')::bigint
$$;
REVOKE ALL ON FUNCTION autenticacao.organizacao_atual() FROM PUBLIC;
REVOKE ALL ON FUNCTION autenticacao.usuario_atual() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION autenticacao.organizacao_atual(), autenticacao.usuario_atual() TO finder_app;

ALTER TABLE organizacoes.organizacao ENABLE ROW LEVEL SECURITY;
CREATE POLICY organizacao_isolada ON organizacoes.organizacao TO finder_app
    USING (id = autenticacao.organizacao_atual());

ALTER TABLE acesso.usuario ENABLE ROW LEVEL SECURITY;
CREATE POLICY usuario_isolado ON acesso.usuario TO finder_app
    USING (organizacao_id = autenticacao.organizacao_atual())
    WITH CHECK (organizacao_id = autenticacao.organizacao_atual());
ALTER TABLE acesso.usuario_permissao ENABLE ROW LEVEL SECURITY;
CREATE POLICY usuario_permissao_isolada ON acesso.usuario_permissao TO finder_app
    USING (organizacao_id = autenticacao.organizacao_atual())
    WITH CHECK (organizacao_id = autenticacao.organizacao_atual());
ALTER TABLE estudantes.perfil ENABLE ROW LEVEL SECURITY;
CREATE POLICY perfil_isolado ON estudantes.perfil TO finder_app
    USING (organizacao_id = autenticacao.organizacao_atual())
    WITH CHECK (organizacao_id = autenticacao.organizacao_atual());
ALTER TABLE oportunidades.oportunidade ENABLE ROW LEVEL SECURITY;
CREATE POLICY oportunidade_isolada ON oportunidades.oportunidade TO finder_app
    USING (organizacao_id = autenticacao.organizacao_atual())
    WITH CHECK (organizacao_id = autenticacao.organizacao_atual());
ALTER TABLE candidaturas.candidatura ENABLE ROW LEVEL SECURITY;
CREATE POLICY candidatura_leitura ON candidaturas.candidatura FOR SELECT TO finder_app
    USING (organizacao_id = autenticacao.organizacao_atual()
        AND (estudante_id = autenticacao.usuario_atual()
             OR EXISTS (SELECT 1 FROM acesso.usuario_permissao up
                        JOIN acesso.permissao p ON p.id = up.permissao_id
                        WHERE up.organizacao_id = autenticacao.organizacao_atual()
                          AND up.usuario_id = autenticacao.usuario_atual()
                          AND p.recurso = 'candidaturas'
                          AND p.acao = 'visualizar_organizacao')));
CREATE POLICY candidatura_criacao ON candidaturas.candidatura FOR INSERT TO finder_app
    WITH CHECK (organizacao_id = autenticacao.organizacao_atual()
        AND estudante_id = autenticacao.usuario_atual());
CREATE POLICY candidatura_atualizacao ON candidaturas.candidatura FOR UPDATE TO finder_app
    USING (organizacao_id = autenticacao.organizacao_atual()
        AND EXISTS (SELECT 1 FROM acesso.usuario_permissao up
                    JOIN acesso.permissao p ON p.id = up.permissao_id
                    WHERE up.organizacao_id = autenticacao.organizacao_atual()
                      AND up.usuario_id = autenticacao.usuario_atual()
                      AND p.recurso = 'candidaturas'
                      AND p.acao = 'alterar_status'))
    WITH CHECK (organizacao_id = autenticacao.organizacao_atual());

CREATE FUNCTION autenticacao.buscar_credenciais(p_login TEXT)
RETURNS TABLE (id BIGINT, organizacao_id BIGINT, nome TEXT, login TEXT, senha_hash TEXT,
    papel TEXT, versao_acesso BIGINT, permissoes TEXT[])
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
    SELECT u.id, u.organizacao_id, u.nome::text, u.login::text, u.senha_hash::text,
           u.papel::text, u.versao_acesso,
           ARRAY(SELECT p.recurso::text || ':' || p.acao::text
                 FROM acesso.usuario_permissao up
                 JOIN acesso.permissao p ON p.id = up.permissao_id
                 WHERE up.organizacao_id = u.organizacao_id AND up.usuario_id = u.id)
    FROM acesso.usuario u
    WHERE u.login = lower(btrim(p_login)) AND u.ativo
$$;
CREATE FUNCTION autenticacao.versao_sessao(p_id BIGINT) RETURNS BIGINT
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
    SELECT versao_acesso FROM acesso.usuario WHERE id = p_id AND ativo
$$;
REVOKE ALL ON FUNCTION autenticacao.buscar_credenciais(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION autenticacao.versao_sessao(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION autenticacao.buscar_credenciais(TEXT), autenticacao.versao_sessao(BIGINT) TO finder_app;
